Repository stakeordie/griptape.js, pull requests merged in 2021-09, with the labels that each got.

#35 Fix: Throw error when undefined viewing key added (#23)
  src/viewing-keys.ts
Labels: bug

#37 feat: Add entropy as part of the context in the Contracts API (#29)
  src/contracts/index.ts
  src/contracts/types.ts
Labels: enhancement

#39 feat: Add support for SNIP-721 contract definition (#31)
  src/contracts/definitions/index.ts
  src/contracts/definitions/snip-721-def.ts
  src/contracts/types.ts
Labels: enhancement

#40 feat: Complete SNIP-20 contract definition (#28)
  src/contracts/definitions/snip-20-def.ts
  src/contracts/types.ts
Labels: enhancement

#55 feat: create base class for Secret Network modules #42
  src/modules/base.ts
  src/modules/governance.ts
  src/modules/index.ts
  src/modules/minting.ts
  src/modules/supply.ts
Labels: enhancement

#56 Add response wrapper for txs responses (#36)
  src/contracts/index.ts
  src/contracts/types.ts
  src/contracts/utils.ts
Labels: enhancement

#61 fix: change type for contracts in `ViewingKeyManager` (#57)
  src/viewing-keys.ts
Labels: bug

#58 feat: Add Mint module #54
  src/modules/minting.ts
Labels: enhancement

#62 feat: Add Slashing module (#51)
  src/modules/index.ts
  src/modules/slashing.ts
Labels: enhancement

#60 feat: Add Supply module (#53)
  src/modules/supply.ts
Labels: enhancement

#68 fix: make `queries` and `messages` optional in `ContractDefinition`
  src/contracts/types.ts
Labels: bug

#65 Add Auth module (#47)
  src/modules/auth.ts
  src/modules/index.ts
Labels: enhancement

#64 Add Bank module #48
  src/modules/bank.ts
  src/modules/index.ts
Labels: enhancement

#75 refactor: Refactor common types between modules (#63)
  src/modules/auth.ts
  src/modules/bank.ts
  src/modules/distribution.ts
  src/modules/governance.ts
  src/modules/minting.ts
  src/modules/slashing.ts
  src/modules/staking.ts
  src/modules/supply.ts
  src/modules/types.ts
Labels: enhancement

#77 refactor: add return types to Snip721Contract (#74)
  src/contracts/definitions/snip-721-def.ts
  src/contracts/types.ts
Labels: enhancement

#78 Release 0.6.0
  .prettierrc
  package.json
  src/bootstrap.ts
  src/contracts/definitions/index.ts
  src/contracts/definitions/snip-20-def.ts
  src/contracts/definitions/snip-721-def.ts
  src/contracts/errors.ts
  src/contracts/index.ts
  src/contracts/types.ts
  src/contracts/utils.ts
  src/modules/auth.ts
  src/modules/bank.ts
  src/modules/base.ts
  src/modules/distribution.ts
  src/modules/governance.ts
  src/modules/index.ts
  src/modules/minting.ts
  src/modules/slashing.ts
  src/modules/staking.ts
  src/modules/supply.ts
  src/modules/types.ts
  src/viewing-keys.ts
  src/wallet.ts
Labels: bug, documentation, enhancement
